name             'aixbase'
maintainer       'Chef Software, Inc.'
maintainer_email 'jdunn@chef.io'
license          'Apache 2.0'
description      'Base cookbook for running AIX systems'
long_description 'Base cookbook for running AIX systems'
version          '0.1.0'

depends 'aix'
supports 'aix', '>= 6.1'
